/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author User
 */
public class VistaInformes extends javax.swing.JPanel {

    Connection conexion;
    JasperReport reporte;
    Map<String, Object> parametros;
    String source;
    String rutaPDF;
    String rutaHTML;
    Boolean compilado = true;

    private static final String DATABASE_PATH = new File("restaurante").getAbsolutePath();
    private static final String DATABASE_URL = "jdbc:sqlite:" + DATABASE_PATH;

    public VistaInformes() {
        initComponents();

        btnGrupo.add(rbtnNormal);
        btnGrupo.add(rbtnGrupos);
        btnGrupo.add(rbtnGrafico);
        rbtnNormal.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupo = new javax.swing.ButtonGroup();
        rbtnNormal = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rbtnGrupos = new javax.swing.JRadioButton();
        rbtnGrafico = new javax.swing.JRadioButton();
        btnPDF = new javax.swing.JToggleButton();
        btnHTML = new javax.swing.JToggleButton();

        rbtnNormal.setText("Historial Reservas");
        rbtnNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNormalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Selecciona el informe a generar:");

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Generar Informes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rbtnGrupos.setText("Reservas por Camarero");

        rbtnGrafico.setText("Reservas por Mesa (Gráfico)");
        rbtnGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnGraficoActionPerformed(evt);
            }
        });

        btnPDF.setText("Generar PDF");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        btnHTML.setText("Generar HTML");
        btnHTML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHTMLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnPDF)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnHTML))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel1))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnGrafico)
                                    .addComponent(rbtnNormal)
                                    .addComponent(rbtnGrupos))))
                        .addGap(0, 108, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(rbtnNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnGrupos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnGrafico)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPDF)
                    .addComponent(btnHTML))
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnNormalActionPerformed

    private void rbtnGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnGraficoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnGraficoActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        source = obtenerRuta();
        rutaPDF = obtenerRutaPDF();

        generarInformePDF(source, rutaPDF);
    }//GEN-LAST:event_btnPDFActionPerformed

    private void btnHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHTMLActionPerformed
        source = obtenerRuta();
        rutaHTML = obtenerRutaHTML();

        generarInformeHTML(source, rutaHTML);
    }//GEN-LAST:event_btnHTMLActionPerformed

    public void generarInformePDF(String source, String rutaPDF) {
        try {
            conexion = DriverManager.getConnection(DATABASE_URL);
            parametros = new HashMap<>();
            parametros.put("autor", "Julian Martinez");

            File sourceFile = new File(source);
            if (!sourceFile.exists()) {
                System.err.println("❌ ERROR: No se encontró el archivo del reporte " + source);
                return;
            }

            if (compilado) {
                reporte = (JasperReport) JRLoader.loadObjectFromFile(source.replace(".jrxml", ".jasper"));
            } else {
                reporte = JasperCompileManager.compileReport(source);
            }

            JasperPrint informe = JasperFillManager.fillReport(reporte, parametros, conexion);
            JasperViewer.viewReport(informe, false);
            JasperExportManager.exportReportToPdfFile(informe, rutaPDF);

            JOptionPane.showMessageDialog(null, "✅ Reporte PDF generado correctamente");

        } catch (JRException | SQLException ex) {
            ex.printStackTrace();
        }
    }

    // ✅ Generar reporte en HTML
    public void generarInformeHTML(String source, String rutaHTML) {
        try {
            conexion = DriverManager.getConnection(DATABASE_URL);
            parametros = new HashMap<>();
            parametros.put("autor", "Julian Martinez");

            File sourceFile = new File(source);
            if (!sourceFile.exists()) {
                System.err.println("❌ ERROR: No se encontró el archivo del reporte " + source);
                return;
            }

            if (compilado) {
                reporte = (JasperReport) JRLoader.loadObjectFromFile(source.replace(".jrxml", ".jasper"));
            } else {
                reporte = JasperCompileManager.compileReport(source);
            }

            JasperPrint informe = JasperFillManager.fillReport(reporte, parametros, conexion);
            JasperViewer.viewReport(informe, false);
            JasperExportManager.exportReportToHtmlFile(informe, rutaHTML);

            JOptionPane.showMessageDialog(null, "✅ Reporte HTML generado correctamente");

        } catch (JRException | SQLException ex) {
            ex.printStackTrace();
        }
    }

    // ✅ Métodos para obtener la ruta de los reportes
    public String obtenerRuta() {
        if (rbtnNormal.isSelected()) {
            return new File("reportes/reporteReservas.jrxml").getAbsolutePath();
        } else if (rbtnGrupos.isSelected()) {
            return new File("reportes/reporteCamarero.jrxml").getAbsolutePath();
        } else if (rbtnGrafico.isSelected()) {
            return new File("reportes/reporteMesas.jrxml").getAbsolutePath();
        } else {
            System.out.println("❌ ERROR: No se seleccionó un tipo de reporte.");
            return null;
        }
    }

    public String obtenerRutaPDF() {
        if (rbtnNormal.isSelected()) {
            return new File("reportes/reportesGenerados/reporteReservas.pdf").getAbsolutePath();
        } else if (rbtnGrupos.isSelected()) {
            return new File("reportes/reportesGenerados/reporteCamarero.pdf").getAbsolutePath();
        } else if (rbtnGrafico.isSelected()) {
            return new File("reportes/reportesGenerados/reporteMesas.pdf").getAbsolutePath();
        } else {
            System.out.println("❌ ERROR: No se seleccionó un tipo de reporte para PDF.");
            return null;
        }
    }

    public String obtenerRutaHTML() {
        if (rbtnNormal.isSelected()) {
            return new File("reportes/reportesGenerados/reporteReservas.html").getAbsolutePath();
        } else if (rbtnGrupos.isSelected()) {
            return new File("reportes/reportesGenerados/reporteCamarero.html").getAbsolutePath();
        } else if (rbtnGrafico.isSelected()) {
            return new File("reportes/reportesGenerados/reporteMesas.html").getAbsolutePath();
        } else {
            System.out.println("❌ ERROR: No se seleccionó un tipo de reporte para HTML.");
            return null;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrupo;
    private javax.swing.JToggleButton btnHTML;
    private javax.swing.JToggleButton btnPDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbtnGrafico;
    private javax.swing.JRadioButton rbtnGrupos;
    private javax.swing.JRadioButton rbtnNormal;
    // End of variables declaration//GEN-END:variables
}
